#!/usr/bin/env python3
"""Add milestone-based growth to SVGs generated by Platane/snk.

The upstream generator intentionally renders a four-segment snake. This small,
dependency-free post-processor keeps its contribution data and route intact,
then adds tail segments that become visible exactly when contribution cells are
eaten. Change the workflow's ``--max-segments`` value when a shorter or longer
tail is preferred later.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from statistics import median


MARKER = "growing-snake:v1"


def _css_block(source: str, declaration: re.Match[str]) -> str:
    """Return the contents of the balanced CSS block after *declaration*."""

    start = source.find("{", declaration.end())
    if start < 0:
        raise ValueError(f"missing CSS block after {declaration.group(0)!r}")

    depth = 0
    for index in range(start, len(source)):
        if source[index] == "{":
            depth += 1
        elif source[index] == "}":
            depth -= 1
            if depth == 0:
                return source[start + 1 : index]

    raise ValueError(f"unterminated CSS block after {declaration.group(0)!r}")


def _consumption_milestones(svg: str) -> list[float]:
    milestones: list[float] = []
    declarations = re.finditer(r"@keyframes\s+c[0-9a-z]+\s*", svg)
    for declaration in declarations:
        block = _css_block(svg, declaration)
        match = re.search(r"(\d+(?:\.\d+)?)%", block)
        if match:
            milestones.append(float(match.group(1)))
    return sorted(set(milestones))


def _snake_timing(svg: str, duration_ms: int) -> tuple[int, float]:
    declaration = re.search(r"@keyframes\s+s0\s*", svg)
    if not declaration:
        raise ValueError("missing s0 snake keyframes")

    block = _css_block(svg, declaration)
    percentages = sorted(
        {float(value) for value in re.findall(r"(\d+(?:\.\d+)?)%", block)}
    )
    deltas = [
        right - left
        for left, right in zip(percentages, percentages[1:])
        if right - left > 0.05
    ]
    if not deltas:
        raise ValueError("cannot infer a snake movement step")

    smallest = min(deltas)
    unit_deltas = [delta for delta in deltas if delta <= smallest + 0.03]
    inferred = round(duration_ms * median(unit_deltas) / 100)
    reset = max(value for value in percentages if value < 100)
    return max(1, inferred), reset


def _select_milestones(values: list[float], count: int) -> list[float]:
    if count <= 0 or not values:
        return []
    if count == 1:
        return [values[0]]
    if len(values) <= count:
        return values

    last = len(values) - 1
    return [values[round(index * last / (count - 1))] for index in range(count)]


def enhance_svg(svg: str, *, max_segments: int = 10) -> str:
    """Return *svg* with a contribution-driven growing tail.

    The added segments reuse the generated head route with a phase delay. Their
    opacity switches on at real cell-consumption percentages, so each visible
    growth event is tied to the contribution animation rather than a timer that
    merely looks plausible.
    """

    if MARKER in svg:
        return svg

    duration_match = re.search(
        r"\.s\s*\{[^}]*?animation\s*:\s*none\s+linear\s+(\d+)ms\s+infinite",
        svg,
    )
    if not duration_match:
        raise ValueError("cannot find the snake animation duration")
    duration_ms = int(duration_match.group(1))

    milestones = _consumption_milestones(svg)
    if not milestones:
        return svg

    snake_rects = list(
        re.finditer(r'<rect\s+class="s\s+s(\d+)"[^>]*/>', svg)
    )
    if not snake_rects:
        raise ValueError("cannot find generated snake segments")

    original_segments = max(int(match.group(1)) for match in snake_rects) + 1
    extra_count = max(0, max_segments - original_segments)
    selected = _select_milestones(milestones, extra_count)
    if not selected:
        return svg

    step_ms, reset = _snake_timing(svg, duration_ms)
    tail_template = snake_rects[-1].group(0)
    styles: list[str] = [
        f"/* {MARKER}; original={original_segments}; max={max_segments} */",
        ".sg{shape-rendering:geometricPrecision;fill:var(--cs);opacity:0}",
    ]
    rects: list[str] = []

    for offset, milestone in enumerate(selected):
        segment = original_segments + offset
        reveal = min(milestone + 0.02, reset - 0.03)
        phase_delay = -(duration_ms - segment * step_ms)
        styles.extend(
            [
                (
                    f"@keyframes sg-grow-{segment}"
                    f"{{0%,{milestone:.2f}%{{opacity:0}}"
                    f"{reveal:.2f}%,{reset - 0.02:.2f}%{{opacity:1}}"
                    f"{reset:.2f}%,100%{{opacity:0}}}}"
                ),
                (
                    f".sg.sg{segment}{{animation-name:s0,sg-grow-{segment};"
                    f"animation-duration:{duration_ms}ms,{duration_ms}ms;"
                    f"animation-delay:{phase_delay}ms,0ms;"
                    "animation-timing-function:linear,steps(1,end);"
                    "animation-iteration-count:infinite,infinite}"
                ),
            ]
        )

        tail = re.sub(
            r'class="s\s+s\d+"',
            f'class="sg sg{segment}"',
            tail_template,
            count=1,
        )
        tail = tail[:-2] + (
            f' data-growth-step="{offset + 1}"'
            f' data-visible-after="{milestone:.2f}%"/>'
        )
        rects.append(tail)

    style_payload = "".join(styles)
    if "</style>" not in svg:
        raise ValueError("cannot find closing style element")
    svg = svg.replace("</style>", style_payload + "</style>", 1)

    first_snake_rect = snake_rects[0].group(0)
    return svg.replace(first_snake_rect, "".join(rects) + first_snake_rect, 1)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Add contribution-driven growth to Platane/snk SVG files."
    )
    parser.add_argument("files", nargs="+", type=Path)
    parser.add_argument("--max-segments", type=int, default=10)
    args = parser.parse_args()

    for path in args.files:
        source = path.read_text(encoding="utf-8")
        enhanced = enhance_svg(source, max_segments=args.max_segments)
        path.write_text(enhanced, encoding="utf-8", newline="")
        added = enhanced.count('class="sg sg')
        print(f"enhanced {path}: {added} growth segments")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
